# Generated by Django 6.0.2 on 2026-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deleted_at_userprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
