# Generated by Django 6.0.2 on 2026-03-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='user',
        ),
    ]
