# Generated by Django 6.0.2 on 2026-03-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_userid_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
