# Generated by Django 6.0.2 on 2026-03-23 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldRolePermissions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldRoles',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldRoleHasPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worldrolepermissions')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worldroles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worlds',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldRules',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stat_slug', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('is_required', models.BooleanField(default=False)),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldRooms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='worldroles',
            name='world_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlds'),
        ),
        migrations.CreateModel(
            name='WorldUserHasRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worldroles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldUserProfiles',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldRoomMessages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2048)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worldrooms')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlduserprofiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldRoomMessageActions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worldroommessages')),
                ('world_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worldrules')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlduserprofiles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
