# Generated by Django 6.0.2 on 2026-03-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldrolehaspermissions',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='worldrolehaspermissions',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='worldroles',
            old_name='world_id',
            new_name='world',
        ),
        migrations.RenameField(
            model_name='worldroommessageactions',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='worldroommessageactions',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='worldroommessageactions',
            old_name='world_rule_id',
            new_name='world_rule',
        ),
        migrations.RenameField(
            model_name='worldroommessages',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='worldroommessages',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='worldrooms',
            old_name='world_id',
            new_name='world',
        ),
        migrations.RenameField(
            model_name='worldrules',
            old_name='world_id',
            new_name='world',
        ),
        migrations.RenameField(
            model_name='worlds',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='worlduserhasroles',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='worlduserhasroles',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='worlduserhasroles',
            old_name='world_id',
            new_name='world',
        ),
        migrations.RenameField(
            model_name='worlduserprofiles',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='worlduserprofiles',
            old_name='world_id',
            new_name='world',
        ),
    ]
