# Generated by Django 6.0.2 on 2026-03-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='World',
            new_name='Worlds',
        ),
        migrations.CreateModel(
            name='WorldRules',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False)),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.worlds')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
