# Generated by Django 6.0.2 on 2026-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_permission_id_worldrolehaspermissions_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldrolehaspermissions',
            options={'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterModelOptions(
            name='worldrolepermissions',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='worldroles',
            options={'verbose_name': 'World Role', 'verbose_name_plural': 'World Roles'},
        ),
        migrations.AlterModelOptions(
            name='worldroommessageactions',
            options={'verbose_name': 'Message Action', 'verbose_name_plural': 'Message Actions'},
        ),
        migrations.AlterModelOptions(
            name='worldroommessages',
            options={'verbose_name': 'Room Message', 'verbose_name_plural': 'Room Messages'},
        ),
        migrations.AlterModelOptions(
            name='worldrooms',
            options={'verbose_name': 'World Room', 'verbose_name_plural': 'World Rooms'},
        ),
        migrations.AlterModelOptions(
            name='worldrules',
            options={'verbose_name': 'World Rule', 'verbose_name_plural': 'World Rules'},
        ),
        migrations.AlterModelOptions(
            name='worlds',
            options={'verbose_name': 'World', 'verbose_name_plural': 'Worlds'},
        ),
        migrations.AlterModelOptions(
            name='worlduserhasroles',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterModelOptions(
            name='worlduserprofiles',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='worlds',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='world_avatars'),
        ),
    ]
