# Generated by Django 6.0.2 on 2026-04-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_worldrolehaspermissions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldrooms',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='world_room_thumbnails'),
        ),
        migrations.AddField(
            model_name='worlduserprofiles',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='world_profile_avatars'),
        ),
    ]
